export const daysOfWeek = {
  0: "Domingo",
  1: "Segunda",
  2: "Terça",
  3: "Quarta",
  4: "Quinta",
  5: "Sexta",
  6: "Sábado",
  domingo: "0",
  segunda: "1",
  terca: "2",
  terça: "2",
  quarta: "3",
  quinta: "4",
  sexta: "5",
  sabado: "6",
};
